### PR TITLE
optimize resource files

### PR DESCRIPTION
**Pull request by rhysdh540**
losslessly decrease the file size of all the sound files using [OptiVorbis](https://github.com/OptiVorbis/OptiVorbis), saves about 3mb in final jar size

### CODE REVIEW

**Comment by Sollace** [comment]
Thanks, but I don't want to risk potentially breaking Minecraft's directional sound. It apparently only works with ogg files that are saved in a certain way.

I've had problems with ones before in another project which just wouldn't play and simply re-exporting them to ogg from audacity without changing anything solved it, so I really don't want to risk having to do that with as many sound files are this mod has.

**Comment by rhysdh540** [comment]
I can't test at the moment, but I'm fairly certain that this process should work fine with Minecraft sounds.

from optivorbis's readme:
>  The [testing] dataset comprised all kinds of Ogg Vorbis files containing mono, stereo, and surround sounds at varying sampling rates, generated by a wide variety of encoders.

if you find any issues with this, please do let me know.

**Comment by AlexTMjugador** [comment]
Hello, OptiVorbis author here, I found this PR by sheer coincidence while searching for OptiVorbis uses 🙂 

As @rhysdh540 stated, and as detailed in the project documentation, OptiVorbis optimizations are designed to be entirely lossless and transparent. Extensive testing, both before the project's release and after e.g. its integration with the [Ambient game engine](https://github.com/AmbientRun/Ambient), confirmed that the audio signal remains identical after standard decoding. Thus, it's highly unlikely for OptiVorbis to cause any issues here.

In particular, Minecraft's directional sound can break when audio files are downmixed from stereo to mono, but OptiVorbis doesn't alter this. Any file in Ogg Vorbis format (`.ogg`), regardless of the encoder used, is compatible with OptiVorbis. (You even can feed OptiVorbis the files it generates, although that's a pointless thing to do.)

I'm also the creator of PackSquash, a related tool for optimizing resource packs that incorporates OptiVorbis. I find it worth noting that the lossy optimizations PackSquash performs, which may require effort to get right, are not powered by OptiVorbis. Currently, OptiVorbis serves as just one component within PackSquash's broader audio processing pipeline. So if any vague recollections of audio optimization issues are based on stuff PackSquash did, please rest assured that OptiVorbis approaches optimization on a narrower scope.

Of course, any non-trivial software lacking formal correctness proofs cannot be guaranteed to be defect-free, so if any issues show up, despite my strong expectations that they won't, I'd be willing to listen and look into fixing them as my time permits 👍

**Comment by Sollace** [comment]
Alright. I guess no reason not to merge it. I'll check how things sound before it gets into a release and flag it if I find anything. Thanks @AlexTMjugador and @rhysdh540

**Pull request merged**
