### PR TITLE
Add translation for Chinese

### PR DESCRIPTION
**Pull request by KrisCris**
- Translation for Chinese
(Btw, why the subtitle displays wood sound when walking on glass?)

### CODE REVIEW

**Comment by Sollace** [comment]
> (Btw, why the subtitle displays wood sound when walking on glass?)
I don't really know what you mean by this. I checked and all the glass subtitles still say glass.

**Comment by Sollace** [comment]
Oh and thanks for the translation! It will be included in the next release.

**Comment by KrisCris** [comment]
When players walking on glass, the subtitle shows wood_creaks or something similar.

**Comment by Sollace** [comment]
It's because most sounds in PF are composed from multiple sounds. In this case the glass stepping acoustic has a little wood in it. You'll probably find a lot of similar cases throughout.

**Comment by KrisCris** [comment]
Yeah, I see! So I turned the subtitle off. Lol

**Comment by Sollace** [comment]
Yaaaah. As do I, lol

**Pull request merged**
